// Tile data for Betrayal at House on the Hill
// Each tile has: id, name, floors it can appear on, door directions, optional card type, description
//
// Door directions: 'N', 'S', 'E', 'W'
// Floors: 'ground', 'upper', 'basement'
// Card types: 'event', 'item', 'omen', or null

export const STARTING_TILES = [
  {
    id: "entrance-hall",
    name: "Entrance Hall",
    floors: ["ground"],
    doors: ["N", "E", "W"],
    cardType: null,
    description: "The front door of the house. There is no turning back.",
  },
  {
    id: "hallway",
    name: "Hallway",
    floors: ["ground"],
    doors: ["N", "S", "E", "W"],
    cardType: null,
    description: "A long hallway stretches before you.",
    connectsTo: "secret-staircase",
  },
  {
    id: "grand-staircase",
    name: "Grand Staircase",
    floors: ["ground"],
    doors: ["S"],
    cardType: null,
    description: "A sweeping staircase leads up... and down.",
    special: "staircase",
    connectsTo: "upper-landing",
  },
  {
    id: "upper-landing",
    name: "Upper Landing",
    floors: ["upper"],
    doors: ["N", "S", "E", "W"],
    cardType: null,
    description: "The stairs creak as you reach the second floor.",
    connectsTo: "grand-staircase",
  },
  {
    id: "basement-landing",
    name: "Basement Landing",
    floors: ["basement"],
    doors: ["N", "S", "E", "W"],
    cardType: null,
    description: "Cold stone stairs lead down into darkness.",
  },
];

export const TILES = [
  {
    id: "armory", // SPECIAL TILE. NEEDS ATTENTION
    name: "Armory",
    floors: ["ground", "basement"],
    doors: ["N", "E"],
    cardType: null,
    description:
      "When you discover this tile, reveal cards from the top of the item deck until you reveal a weapon. <br> Take it and bury the rest.",
    discoverEffect: "armory",
  },
  // {
  //   id: "ballroom",
  //   name: "Ballroom",
  //   floors: ["ground"],
  //   doors: ["N", "E", "S", "W"],
  //   cardType: "omen",
  //   // description: "The floorboards groan beneath your feet.",
  // },
  // {
  //   id: "bloody-room",
  //   name: "Bloody Room",
  //   floors: ["ground", "upper"],
  //   doors: ["N", "E"],
  //   cardType: "item",
  //   // description: "A massive pipe organ dominates the room.",
  // },
  // {
  //   id: "catacombs",
  //   name: "Catacombs",
  //   floors: ["basement"],
  //   doors: ["N", "E", "S", "W"],
  //   cardType: "omen",
  //   // description: "Stained glass windows cast eerie colored light.",
  // },
  // {
  //   id: "chapel",
  //   name: "Chapel",
  //   floors: ["ground"],
  //   doors: ["N", "S"],
  //   cardType: "omen",
  //   description: "When you discover this tile, gain 1 Sanity",
  //   discoverGain: { stat: "sanity", amount: 1 },
  // },
  // {
  //   id: "charred-room",
  //   name: "Charred Room",
  //   floors: ["ground", "upper"],
  //   doors: ["N", "E"],
  //   cardType: "omen",
  //   // description: "Thick dust coats every surface.",
  // },
  // {
  //   id: "chasm",
  //   name: "Chasm",
  //   floors: ["basement"],
  //   doors: ["N", "S"],
  //   cardType: "event",
  //   // description: "Something burned here. The walls are blackened and cracked.",
  // },
  // {
  //   id: "collapsed-room", // SPECIAL TILE. NEEDS ATTENTION
  //   name: "Collapsed Room",
  //   floors: ["ground", "upper"],
  //   doors: ["N", "E"],
  //   cardType: null,
  //   description:
  //     "If you end your turn on this tile, make a speed roll. 5+: Nothing happens. 4-0: Place your explorer on the Basement Landing and take one die of Physical damage",
  //   endOfTurn: "collapsed",
  // },
  // {
  //   id: "conservatory",
  //   name: "Conservatory",
  //   floors: ["ground"],
  //   doors: ["N", "S"],
  //   cardType: "item",
  //   // description: "Broken furniture and scattered debris fill this room.",
  // },
  // {
  //   id: "cramped-passageway",
  //   name: "Cramped Passageway",
  //   floors: ["ground", "upper", "basement"],
  //   doors: ["N", "E", "S", "W"],
  //   cardType: "event",
  //   // description: "Small, cramped rooms with narrow beds.",
  // },
  // {
  //   id: "crawlspace",
  //   name: "Crawlspace",
  //   floors: ["upper", "basement"],
  //   doors: ["N", "E", "W"],
  //   cardType: "event",
  //   // description: "Rusted surgical tools gleam on metal trays.",
  // },
  // {
  //   id: "dining-room",
  //   name: "Dining Room",
  //   floors: ["ground"],
  //   doors: ["N", "E", "S", "W"],
  //   cardType: "event",
  //   // description: "Dead plants fill crumbling pots along the windows.",
  // },
  // {
  //   id: "furnace-room",
  //   name: "Furnace Room",
  //   floors: ["basement"],
  //   doors: ["E", "S", "W"],
  //   cardType: "event",
  //   description: "If you end your turn on this tile, take one die of Physical damage",
  //   endOfTurn: "furnace",
  // },
  // {
  //   id: "gallery",
  //   name: "Gallery",
  //   floors: ["upper"],
  //   doors: ["N", "S"],
  //   cardType: "event",
  //   description: "Leads to Ballroom",
  //   connectsTo: "ballroom",
  // },
  // {
  //   id: "game-room",
  //   name: "Game Room",
  //   floors: ["ground", "basement"],
  //   doors: ["N", "S", "E", "W"],
  //   cardType: "item",
  //   // description: "Overgrown and wild, with strange plants.",
  // },
  // {
  //   id: "graveyard",
  //   name: "Graveyard",
  //   floors: ["ground"],
  //   doors: ["N", "E"],
  //   cardType: "omen",
  //   description: "Leads to the Underground Cavern",
  //   connectsTo: "underground-cavern",

  // },
  // {
  //   id: "guest-quarters",
  //   name: "Guest Quarters",
  //   floors: ["ground", "upper"],
  //   doors: ["N", "E"],
  //   cardType: "event",
  //   // description: "Crooked headstones jut from the earth.",
  // },
  // {
  //   id: "gymnasium",
  //   name: "Gymnasium",
  //   floors: ["ground", "upper"],
  //   doors: ["N", "W"],
  //   cardType: null,
  //   description: "When you discover this tile, gain 1 Speed",
  //   discoverGain: { stat: "speed", amount: 1 },
  // },
  {
    id: "junk-room",
    name: "Junk Room",
    floors: ["ground", "upper"],
    doors: ["N", "E", "S"],
    cardType: "item",
    description: "When you discover this tile, place an Obstacle token on it",
    discoverEffect: "junk-room",
  },
  // {
  //   id: "kitchen",
  //   name: "Kitchen",
  //   floors: ["ground"],
  //   doors: ["N", "S"],
  //   cardType: "event",
  //   // description: "A child's bedroom. Something is wrong with the dolls.",
  // },
  // {
  //   id: "laboratory",
  //   name: "Laboratory",
  //   floors: ["ground"],
  //   doors: ["N", "E"],
  //   cardType: "event",
  //   // description: "A dizzying view of the grounds below.",
  // },
  // {
  //   id: "larder",
  //   name: "Larder",
  //   floors: ["ground"],
  //   doors: ["N", "W"],
  //   cardType: null,
  //   description: "When you discover this tile, gain 1 Might",
  //   discoverGain: { stat: "might", amount: 1 },
  // },
  {
    id: "laundry-chute",
    name: "Laundry Chute",
    floors: ["ground"],
    doors: ["N"],
    cardType: null,
    description:
      "Leads to the Basement Landing. If you end your turn on this tile, place your explorer on the Basement Landing",
    endOfTurn: "laundry-chute",
  },
  // {
  //   id: "library",
  //   name: "Library",
  //   floors: ["ground", "basement"],
  //   doors: ["N", "E", "S"],
  //   cardType: "omen",
  //   description: "When you discover this tile, gain 1 Knowledge",
  //   discoverGain: { stat: "knowledge", amount: 1 },
  // },
  // {
  //   id: "mystic-elevator",
  //   name: "Mystic Elevator",
  //   floors: ["ground", "upper", "basement"],
  //   doors: ["N"],
  //   cardType: null,
  //   description:
  //     "Once per turn when you enter this tile, you may roll two dice. Move the Mystic Elevator to an open doorway on: 4+: Any region. 3: Upper Floor. 2: Ground Floor. 1-0: Basement",
  // },
  // {
  //   id: "nursery",
  //   name: "Nursery",
  //   floors: ["ground", "basement"],
  //   doors: ["N", "E"],
  //   cardType: "omen",
  //   // description: "A pentagram is carved into the stone floor.",
  // },
  // {
  //   id: "observatory",
  //   name: "Observatory",
  //   floors: ["upper"],
  //   doors: ["N", "S", "E"],
  //   cardType: "omen",
  //   // description: "Narrow stairs lead upward.",
  // },
  // {
  //   id: "operating-theater",
  //   name: "Operating Theater",
  //   floors: ["basement", "upper"],
  //   doors: ["N", "E"],
  //   cardType: "item",
  //   // description: "Racks of dusty bottles line the walls.",
  // },
  // {
  //   id: "organ-room",
  //   name: "Organ Room",
  //   floors: ["basement", "upper"],
  //   doors: ["E", "S"],
  //   cardType: "event",
  //   // description: "A dark chute leads somewhere you don't want to go.",
  // },
  {
    id: "panic-room",
    name: "Panic Room",
    floors: ["basement"],
    doors: ["N"],
    cardType: "omen",
    description:
      "When you discover this tile, if the Secret Stairs tile has not been placed, find it in the tile stack and place it at any open doorway in the Basement. Then, shuffle the tile stack.",
    discoverEffect: "panic-room",
  },
  // {
  //   id: "primary-bedroom",
  //   name: "Primary Bedroom",
  //   floors: ["ground", "upper"],
  //   doors: ["N", "E", "S"],
  //   cardType: "omen",
  //   // description: "Bubbling beakers and strange apparatus.",
  // },
  // {
  //   id: "ritual-room",
  //   name: "Ritual Room",
  //   floors: ["basement"],
  //   doors: ["N", "E"],
  //   cardType: "omen",
  //   // description: "Shelves of preserved foods... some are moving.",
  // },
  // {
  //   id: "salon",
  //   name: "Salon",
  //   floors: ["ground", "upper"],
  //   doors: ["N", "E"],
  //   cardType: "event",
  //   // description: "Crates and barrels fill this room.",
  // },
  {
    id: "secret-staircase",
    name: "Secret Staircase",
    floors: ["basement"],
    doors: ["N"],
    cardType: null,
    description: "Leads to the Hallway",
    connectsTo: "hallway",
  },
  // {
  //   id: "soundproofed-room",
  //   name: "Soundproofed Room",
  //   floors: ["upper", "basement"],
  //   doors: ["N", "E", "S"],
  //   cardType: "omen",
  //   // description: "A pentagram is carved into the stone floor.",
  // },
  // {
  //   id: "specimen-room",
  //   name: "Specimen Room",
  //   floors: ["ground", "upper"],
  //   doors: ["E", "W"],
  //   cardType: "omen",
  //   // description: "Narrow stairs lead upward.",
  // },
  // {
  //   id: "statuary-corridor",
  //   name: "Statuary Corridor",
  //   floors: ["upper"],
  //   doors: ["N", "S"],
  //   cardType: "event",
  //   // description: "Racks of dusty bottles line the walls.",
  // },
  // {
  //   id: "tower",
  //   name: "Tower",
  //   floors: ["upper"],
  //   doors: ["N", "S"],
  //   cardType: "event",
  //   // description: "A dark chute leads somewhere you don't want to go.",
  // },
  // {
  //   id: "underground-cavern",
  //   name: "Underground Cavern",
  //   floors: ["basement"],
  //   doors: ["N", "E", "S", "W"],
  //   cardType: "event",
  //   description: "Leads to the Graveyard",
  //   connectsTo: "graveyard",
  // },
  // {
  //   id: "underground-lake",
  //   name: "Underground Lake",
  //   floors: ["basement"],
  //   doors: ["N", "E"],
  //   cardType: "event",
  //   // description: "Bubbling beakers and strange apparatus.",
  // },
  // {
  //   id: "vault",
  //   name: "Vault",
  //   floors: ["basement"],
  //   doors: ["N"],
  //   cardType: "item",
  //   // description: "Shelves of preserved foods... some are moving.",
  // },
  // {
  //   id: "winter-bedroom",
  //   name: "Winter Bedroom",
  //   floors: ["ground", "upper"],
  //   doors: ["N", "E"],
  //   cardType: "omen",
  //   // description: "Crates and barrels fill this room.",
  // },
];

// Shuffle an array (Fisher-Yates)
function shuffle(array) {
  const shuffled = [...array];
  for (let i = shuffled.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]];
  }
  return shuffled;
}

export function createTileStack() {
  return shuffle(TILES);
}
