// Tile data for Betrayal at House on the Hill
// Each tile has: id, name, floors it can appear on, door directions, optional card type, description
//
// Door directions: 'N', 'S', 'E', 'W'
// Floors: 'ground', 'upper', 'basement'
// Card types: 'event', 'item', 'omen', or null

export const STARTING_TILES = [
  {
    id: "entrance-hall",
    name: "Entrance Hall",
    floors: ["ground"],
    doors: ["N", "E", "W"],
    cardType: null,
  },
  {
    id: "hallway",
    name: "Hallway",
    floors: ["ground"],
    doors: ["N", "S", "E", "W"],
    cardType: null,
    description: "Leads to the Secret Staircase",
    connectsTo: "secret-staircase",
  },
  {
    id: "grand-staircase",
    name: "Grand Staircase",
    floors: ["ground"],
    doors: ["S"],
    cardType: null,
    description: "Leads to the Upper Landing",
    special: "staircase",
    connectsTo: "upper-landing",
  },
  {
    id: "upper-landing",
    name: "Upper Landing",
    floors: ["upper"],
    doors: ["N", "S", "E", "W"],
    cardType: null,
    description: "Leads to The Grand Staircase",
    connectsTo: "grand-staircase",
  },
  {
    id: "basement-landing",
    name: "Basement Landing",
    floors: ["basement"],
    doors: ["N", "S", "E", "W"],
    cardType: null,
  },
];

export const TILES = [
  {
    id: "armory",
    name: "Armory",
    floors: ["ground", "basement"],
    doors: ["N", "E"],
    cardType: null,
    description:
      "When you discover this tile, reveal cards from the top of the item deck until you reveal a weapon. Take it and bury the rest.",
    discoverEffect: "armory",
  },
  {
    id: "ballroom",
    name: "Ballroom",
    floors: ["ground"],
    doors: ["N", "E", "S", "W"],
    cardType: "omen",
  },
  {
    id: "bloody-room",
    name: "Bloody Room",
    floors: ["ground", "upper"],
    doors: ["N", "E"],
    cardType: "item",
  },
  {
    id: "catacombs",
    name: "Catacombs",
    floors: ["basement"],
    doors: ["N", "E", "S", "W"],
    cardType: "omen",
  },
  {
    id: "chapel",
    name: "Chapel",
    floors: ["ground"],
    doors: ["N", "S"],
    cardType: "omen",
    description: "When you discover this tile, gain 1 Sanity",
    discoverGain: { stat: "sanity", amount: 1 },
  },
  {
    id: "charred-room",
    name: "Charred Room",
    floors: ["ground", "upper"],
    doors: ["N", "E"],
    cardType: "omen",
  },
  {
    id: "chasm",
    name: "Chasm",
    floors: ["basement"],
    doors: ["N", "S"],
    cardType: "event",
  },
  {
    id: "collapsed-room",
    name: "Collapsed Room",
    floors: ["ground", "upper"],
    doors: ["N", "E"],
    cardType: null,
    description:
      "If you end your turn on this tile, make a speed roll. 5+: Nothing happens. 4-0: Place your explorer on the Basement Landing and take one die of Physical damage",
    endOfTurn: "collapsed",
  },
  {
    id: "conservatory",
    name: "Conservatory",
    floors: ["ground"],
    doors: ["N", "S"],
    cardType: "item",
  },
  {
    id: "cramped-passageway",
    name: "Cramped Passageway",
    floors: ["ground", "upper", "basement"],
    doors: ["N", "E", "S", "W"],
    cardType: "event",
  },
  {
    id: "crawlspace",
    name: "Crawlspace",
    floors: ["upper", "basement"],
    doors: ["N", "E", "W"],
    cardType: "event",
  },
  {
    id: "dining-room",
    name: "Dining Room",
    floors: ["ground"],
    doors: ["N", "E", "S", "W"],
    cardType: "event",
  },
  {
    id: "furnace-room",
    name: "Furnace Room",
    floors: ["basement"],
    doors: ["E", "S", "W"],
    cardType: "event",
    description: "If you end your turn on this tile, take one die of Physical damage",
    endOfTurn: "furnace",
  },
  {
    id: "gallery",
    name: "Gallery",
    floors: ["upper"],
    doors: ["N", "S"],
    cardType: "event",
    description: "Leads to Ballroom",
    connectsTo: "ballroom",
  },
  {
    id: "game-room",
    name: "Game Room",
    floors: ["ground", "basement"],
    doors: ["N", "S", "E", "W"],
    cardType: "item",
  },
  {
    id: "graveyard",
    name: "Graveyard",
    floors: ["ground"],
    doors: ["N", "E"],
    cardType: "omen",
    description: "Leads to the Underground Cavern",
    connectsTo: "underground-cavern",
  },
  {
    id: "guest-quarters",
    name: "Guest Quarters",
    floors: ["ground", "upper"],
    doors: ["N", "E"],
    cardType: "event",
  },
  {
    id: "gymnasium",
    name: "Gymnasium",
    floors: ["ground", "upper"],
    doors: ["N", "W"],
    cardType: null,
    description: "When you discover this tile, gain 1 Speed",
    discoverGain: { stat: "speed", amount: 1 },
  },
  {
    id: "junk-room",
    name: "Junk Room",
    floors: ["ground", "upper"],
    doors: ["N", "E", "S"],
    cardType: "item",
    description: "When you discover this tile, place an Obstacle token on it",
    discoverEffect: "junk-room",
  },
  {
    id: "kitchen",
    name: "Kitchen",
    floors: ["ground"],
    doors: ["N", "S"],
    cardType: "event",
  },
  {
    id: "laboratory",
    name: "Laboratory",
    floors: ["ground"],
    doors: ["N", "E"],
    cardType: "event",
  },
  {
    id: "larder",
    name: "Larder",
    floors: ["ground"],
    doors: ["N", "W"],
    cardType: null,
    description: "When you discover this tile, gain 1 Might",
    discoverGain: { stat: "might", amount: 1 },
  },
  {
    id: "laundry-chute",
    name: "Laundry Chute",
    floors: ["ground"],
    doors: ["N"],
    cardType: null,
    description:
      "Leads to the Basement Landing. If you end your turn on this tile, place your explorer on the Basement Landing",
    endOfTurn: "laundry-chute",
  },
  {
    id: "library",
    name: "Library",
    floors: ["ground", "basement"],
    doors: ["N", "E", "S"],
    cardType: "omen",
    description: "When you discover this tile, gain 1 Knowledge",
    discoverGain: { stat: "knowledge", amount: 1 },
  },
  {
    id: "mystic-elevator",
    name: "Mystic Elevator",
    floors: ["ground", "upper", "basement"],
    doors: ["N"],
    cardType: null,
    description:
      "Once per turn when you enter this tile, you may roll two dice. Move the Mystic Elevator to an open doorway on: 4+: any floor. 3: Upper Floor. 2: Ground Floor. 1-0: Basement. This move is free, and your explorer moves with the elevator.",
    enterEffect: "mystic-elevator",
  },
  {
    id: "nursery",
    name: "Nursery",
    floors: ["ground", "basement"],
    doors: ["N", "E"],
    cardType: "omen",
  },
  {
    id: "observatory",
    name: "Observatory",
    floors: ["upper"],
    doors: ["N", "S", "E"],
    cardType: "omen",
  },
  {
    id: "operating-theater",
    name: "Operating Theater",
    floors: ["basement", "upper"],
    doors: ["N", "E"],
    cardType: "item",
  },
  {
    id: "organ-room",
    name: "Organ Room",
    floors: ["basement", "upper"],
    doors: ["E", "S"],
    cardType: "event",
  },
  {
    id: "panic-room",
    name: "Panic Room",
    floors: ["basement"],
    doors: ["N"],
    cardType: "omen",
    description:
      "When you discover this tile, if the Secret Stairs tile has not been placed, find it in the tile stack and place it at any open doorway in the Basement. Then, shuffle the tile stack.",
    discoverEffect: "panic-room",
  },
  {
    id: "primary-bedroom",
    name: "Primary Bedroom",
    floors: ["ground", "upper"],
    doors: ["N", "E", "S"],
    cardType: "omen",
  },
  {
    id: "ritual-room",
    name: "Ritual Room",
    floors: ["basement"],
    doors: ["N", "E"],
    cardType: "omen",
  },
  {
    id: "salon",
    name: "Salon",
    floors: ["ground", "upper"],
    doors: ["N", "E"],
    cardType: "event",
  },
  {
    id: "secret-staircase",
    name: "Secret Staircase",
    floors: ["basement"],
    doors: ["N"],
    cardType: null,
    description: "Leads to the Hallway",
    connectsTo: "hallway",
  },
  {
    id: "soundproofed-room",
    name: "Soundproofed Room",
    floors: ["upper", "basement"],
    doors: ["N", "E", "S"],
    cardType: "omen",
  },
  {
    id: "specimen-room",
    name: "Specimen Room",
    floors: ["ground", "upper"],
    doors: ["E", "W"],
    cardType: "omen",
  },
  {
    id: "statuary-corridor",
    name: "Statuary Corridor",
    floors: ["upper"],
    doors: ["N", "S"],
    cardType: "event",
  },
  {
    id: "tower",
    name: "Tower",
    floors: ["upper"],
    doors: ["N", "S"],
    cardType: "event",
  },
  {
    id: "underground-cavern",
    name: "Underground Cavern",
    floors: ["basement"],
    doors: ["N", "E", "S", "W"],
    cardType: "event",
    description: "Leads to the Graveyard",
    connectsTo: "graveyard",
  },
  {
    id: "underground-lake",
    name: "Underground Lake",
    floors: ["basement"],
    doors: ["N", "E"],
    cardType: "event",
  },
  {
    id: "vault",
    name: "Vault",
    floors: ["basement"],
    doors: ["N"],
    cardType: "item",
  },
  {
    id: "winter-bedroom",
    name: "Winter Bedroom",
    floors: ["ground", "upper"],
    doors: ["N", "E"],
    cardType: "omen",
  },
];

// Shuffle an array (Fisher-Yates)
function shuffle(array) {
  const shuffled = [...array];
  for (let i = shuffled.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]];
  }
  return shuffled;
}

export function createTileStack() {
  return shuffle(TILES);
}
